language: bash

script:
    - bash scripts/build_push.sh
deploy:
  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
  file: "releases/contiv-[0-9]*tgz"
  skip_cleanup: true
  on:
    master: true

